"""
This type stub file was generated by pyright.
"""

ignore_values = ...
ignore_doctypes = ...

def import_files(
    module, dt=..., dn=..., force=..., pre_process=..., reset_permissions=...
): ...
def import_file(
    module, dt, dn, force=..., pre_process=..., reset_permissions=...
):  # -> bool | None:
    """Sync a file from txt if modifed, return false if not updated"""
    ...

def get_file_path(module, dt, dn): ...
def import_file_by_path(
    path,
    force=...,
    data_import=...,
    pre_process=...,
    ignore_version=...,
    reset_permissions=...,
    for_sync=...,
): ...
def read_doc_from_file(path): ...
def import_doc(
    docdict,
    force=...,
    data_import=...,
    pre_process=...,
    ignore_version=...,
    reset_permissions=...,
): ...
