"""
This type stub file was generated by pyright.
"""

import frappe

def extract_item_codes(message): ...
def format_item_code(item_code): ...
@frappe.whitelist()
def get_item_codes_from_ingka_pagelinks(text): ...
