"""
This type stub file was generated by pyright.
"""

from __future__ import unicode_literals

import frappe

def run_webhooks(doc, method):  # -> None:
    """Run webhooks for this method"""
    ...
