"""
This type stub file was generated by pyright.
"""

import frappe

def get_email_accounts(user=...): ...
@frappe.whitelist()
def create_email_flag_queue(names, action):  # -> None:
    """create email flag queue to mark email either as read or unread"""
    ...

@frappe.whitelist()
def mark_as_closed_open(communication, status):  # -> None:
    """Set status to open or close"""
    ...

@frappe.whitelist()
def move_email(communication, email_account):  # -> None:
    """Move email to another email account."""
    ...

@frappe.whitelist()
def mark_as_trash(communication):  # -> None:
    """Set email status to trash."""
    ...

@frappe.whitelist()
def mark_as_spam(communication, sender):  # -> None:
    """Set email status to spam."""
    ...

def link_communication_to_document(
    doc, reference_doctype, reference_name, ignore_communication_links
): ...
