"""
This type stub file was generated by pyright.
"""

def send(email, append_to=..., retry=...):  # -> None:
    """Deprecated: Send the message or add it to Outbox Email"""
    ...

def get_outgoing_email_account(
    raise_exception_not_set=..., append_to=..., sender=...
):  # -> None:
    """Returns outgoing email account based on `append_to` or the default
    outgoing account. If default outgoing account is not found, it will
    try getting settings from `site_config.json`."""
    ...

def get_default_outgoing_email_account(raise_exception_not_set=...):  # -> None:
    """conf should be like:
    {
     "mail_server": "smtp.example.com",
     "mail_port": 587,
     "use_tls": 1,
     "mail_login": "emails@example.com",
     "mail_password": "Super.Secret.Password",
     "auto_email_id": "emails@example.com",
     "email_sender_name": "Example Notifications",
     "always_use_account_email_id_as_sender": 0,
     "always_use_account_name_as_sender_name": 0
    }
    """
    ...

class SMTPServer:
    def __init__(
        self,
        login=...,
        password=...,
        server=...,
        port=...,
        use_tls=...,
        use_ssl=...,
        append_to=...,
    ) -> None: ...
    def setup_email_account(self, append_to=..., sender=...): ...
    @property
    def sess(self):  # -> SMTP_SSL | SMTP | None:
        """get session"""
        ...
