env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - prettier
parserOptions:
  ecmaVersion: 9
  sourceType: module
root: true
globals:
  comfort: true
  frappe: true
  cur_frm: true
  cur_dialog: true
  cur_page: true
  cur_list: true
  cur_tree: true
  __: true
  locals: true
  refresh_field: true
  $: true
  format_currency: true
  format_number: true
  get_number_format: true
  get_currency_symbol: true
