repos:
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.19.4
      hooks:
          - id: pyupgrade
            args: ["--py37-plus"]

    - repo: https://github.com/psf/black
      rev: 19.3b0
      hooks:
          - id: black

    - repo: https://github.com/pycqa/isort
      rev: 5.9.1
      hooks:
          - id: isort
            files: ".*"
            args: [--profile=black]

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v7.30.0
      hooks:
          - id: eslint
            args:
                - "--fix"

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.3.2
      hooks:
          - id: prettier

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: check-json
          - id: check-yaml
          - id: check-added-large-files
          - id: name-tests-test
          - id: requirements-txt-fixer
