exclude: yarn.lock|CHANGELOG.md

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.28.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        exclude: doctype/.*.json

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: [-c, .bandit.yaml]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.0.0-rc.0
    hooks:
      - id: eslint
        args: [--fix]
        additional_dependencies:
          - eslint@8.0.0-beta.1
          - eslint-plugin-prettier

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
      - id: setup-cfg-fmt
