"""
This type stub file was generated by pyright.
"""

def rename(doctype, fieldname, newname):  # -> None:
    """rename docfield"""
    ...

def update_single(f, new):  # -> None:
    """update in tabSingles"""
    ...

def update_table(f, new):  # -> None:
    """update table"""
    ...

def update_parent_field(f, new):  # -> None:
    """update 'parentfield' in tables"""
    ...

def get_change_column_query(f, new):  # -> str | None:
    """generate change fieldname query"""
    ...

def supports_translation(fieldtype): ...
