"""
This type stub file was generated by pyright.
"""

dynamic_link_queries = ...

def get_dynamic_link_map(for_delete=...):  # -> dict[Unknown, Unknown]:
    """Build a map of all dynamically linked tables. For example,
            if Note is dynamically linked to ToDo, the function will return
            `{"Note": ["ToDo"], "Sales Invoice": ["Journal Entry Detail"]}`

    Note: Will not map single doctypes
    """
    ...

def get_dynamic_links():  # -> list[Unknown]:
    """Return list of dynamic link fields as DocField.
    Uses cache if possible"""
    ...
