"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class Version(Document):
    def set_diff(self, old, new):  # -> bool:
        """Set the data property with the diff of the docs if present"""
        ...
    def for_insert(self, doc): ...
    def get_data(self): ...

def get_diff(old, new, for_child=...):  # -> None:
    """Get diff between 2 document objects

    If there is a change, then returns a dict like:

            {
                    "changed"    : [[fieldname1, old, new], [fieldname2, old, new]],
                    "added"      : [[table_fieldname1, {dict}], ],
                    "removed"    : [[table_fieldname1, {dict}], ],
                    "row_changed": [[table_fieldname1, row_name1, row_index,
                            [[child_fieldname1, old, new],
                            [child_fieldname2, old, new]], ]
                    ],

            }"""
    ...

def on_doctype_update(): ...
