"""
This type stub file was generated by pyright.
"""

import functools

@functools.lru_cache(maxsize=1024)
def get_first_party_apps():  # -> list[Unknown]:
    """Get list of all apps under orgs: frappe. erpnext from GitHub"""
    ...

def render_table(data): ...
def add_line_after(function):  # -> (*args: Unknown, **kwargs: Unknown) -> Unknown:
    """Adds an extra line to STDOUT after the execution of a function this decorates"""
    ...

def add_line_before(function):  # -> (*args: Unknown, **kwargs: Unknown) -> Unknown:
    """Adds an extra line to STDOUT before the execution of a function this decorates"""
    ...

def log(message, colour=...):  # -> None:
    """Coloured log outputs to STDOUT"""
    ...

def warn(message, category=...): ...
