"""
This type stub file was generated by pyright.
"""

def sync_fixtures(app=...):  # -> None:
    """Import, overwrite fixtures from `[app]/fixtures`"""
    ...

def import_custom_scripts(app):  # -> None:
    """Import custom scripts from `[app]/fixtures/custom_scripts`"""
    ...

def export_fixtures(app=...):  # -> None:
    """Export fixtures as JSON to `[app]/fixtures`"""
    ...
