"""
This type stub file was generated by pyright.
"""

GRID_SIZE = ...
BORDER_SIZE = ...
SQUARE_SIZE = ...

class Identicon:
    def __init__(self, str_, background=...) -> None:
        """
        `str_` is the string used to generate the identicon.
        `background` is the background of the identicon.
        """
        ...
    def digest(self, str_):  # -> int:
        """
        Returns a md5 numeric hash
        """
        ...
    def calculate(self):  # -> None:
        """
        Creates the identicon.
        First three bytes are used to generate the color,
        remaining bytes are used to create the drawing
        """
        ...
    def generate(self):  # -> None:
        """
        Save and show calculated identicon
        """
        ...
    def base64(self, format=...):  # -> str:
        """
        usage:  i = Identicon('xx')
                        print(i.base64())
        return: this image's base64 code
        created by: liuzheng712
        bug report: https://github.com/liuzheng712/identicons/issues
        """
        ...
