"""
This type stub file was generated by pyright.
"""

def resize_images(path, maxdim=...): ...
def strip_exif_data(content, content_type):  # -> bytes:
    """Strips EXIF from image files which support it.

    Works by creating a new Image object which ignores exif by
    default and then extracts the binary data back into content.

    Returns:
            Bytes: Stripped image content
    """
    ...
