"""
This type stub file was generated by pyright.
"""

def test_password_strength(
    password, user_inputs=...
):  # -> dict[str, Unknown | int | float | list[Unknown]]:
    """Wrapper around zxcvbn.password_strength"""
    ...

default_feedback = ...

def get_feedback(
    score, sequence
):  # -> dict[str, str | list[Unknown]] | dict[str, str | list[Any]] | dict[str, Unknown | str | list[Unknown]] | dict[str, Unknown | list[Unknown]] | dict[str, list[Unknown]]:
    """
    Returns the feedback dictionary consisting of ("warning","suggestions") for the given sequences.
    """
    ...

def get_match_feedback(
    match, is_sole_match
):  # -> dict[str, Unknown | str | list[Unknown]] | dict[str, Unknown | list[Unknown]] | dict[str, list[Unknown]] | None:
    """
    Returns feedback as a dictionary for a certain match
    """
    ...

def get_dictionary_match_feedback(
    match, is_sole_match
):  # -> dict[str, Unknown | str | list[Unknown]]:
    """
    Returns feedback for a match that is found in a dictionary
    """
    ...
