"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class DomainSettings(Document):
    def set_active_domains(self, domains): ...
    def on_update(self): ...
    def restrict_roles_and_modules(self):  # -> None:
        """Disable all restricted roles and set `restrict_to_domain` property in Module Def"""
        ...

def get_active_domains():
    """get the domains set in the Domain Settings as active domain"""
    ...

def get_active_modules():
    """get the active modules from Module Def"""
    ...
