"""
This type stub file was generated by pyright.
"""

def resolve_redirect(path):  # -> None:
    """
    Resolve redirects from hooks

    Example:

            website_redirect = [
                    # absolute location
                    {"source": "/from", "target": "https://mysite/from"},

                    # relative location
                    {"source": "/from", "target": "/main"},

                    # use regex
                    {"source": r"/from/(.*)", "target": r"/main/\1"}
                    # use r as a string prefix if you use regex groups or want to escape any string literal
            ]
    """
    ...
