#!/bin/bash
set -e

echo "\
ADMIN_PASSWORD=$ADMIN_PASSWORD
DB_PASSWORD=$DB_PASSWORD
DOMAIN=$DOMAIN
LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
FRAPPE_VERSION=$(awk -F '"' '/reqd_frappe_version/{print $2}' ../comfort/hooks.py)
COMFORT_VERSION=$COMFORT_VERSION" \
  >.env
