"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

class AccessLog(Document): ...

@frappe.whitelist()
def make_access_log(
    doctype=...,
    document=...,
    method=...,
    file_type=...,
    report_name=...,
    filters=...,
    page=...,
    columns=...,
): ...
