"""
This type stub file was generated by pyright.
"""

def handle():  # -> Response:
    """
    Handler for `/api` methods

    ### Examples:

    `/api/method/{methodname}` will call a whitelisted method

    `/api/resource/{doctype}` will query a table
            examples:
            - `?fields=["name", "owner"]`
            - `?filters=[["Task", "name", "like", "%005"]]`
            - `?limit_start=0`
            - `?limit_page_length=20`

    `/api/resource/{doctype}/{name}` will point to a resource
            `GET` will return doclist
            `POST` will insert
            `PUT` will update
            `DELETE` will delete

    `/api/resource/{doctype}/{name}?run_method={method}` will run a whitelisted controller method
    """
    ...

def get_request_form_data(): ...
def validate_auth():  # -> None:
    """
    Authenticate and sets user for the request.
    """
    ...

def validate_oauth(authorization_header):  # -> None:
    """
    Authenticate request using OAuth and set session user

    Args:
            authorization_header (list of str): The 'Authorization' header containing the prefix and token
    """
    ...

def validate_auth_via_api_keys(authorization_header):  # -> None:
    """
    Authenticate request using API keys and set session user

    Args:
            authorization_header (list of str): The 'Authorization' header containing the prefix and token
    """
    ...

def validate_api_key_secret(
    api_key, api_secret, frappe_authorization_source=...
):  # -> None:
    """frappe_authorization_source to provide api key and secret for a doctype apart from User"""
    ...

def validate_auth_via_hooks(): ...
