"""
This type stub file was generated by pyright.
"""

from werkzeug.middleware.shared_data import SharedDataMiddleware

class StaticDataMiddleware(SharedDataMiddleware):
    def __call__(self, environ, start_response): ...
    def get_directory_loader(self, directory): ...
