"""
This type stub file was generated by pyright.
"""

import frappe

@frappe.whitelist()
def add(
    doctype,
    name,
    user=...,
    read=...,
    write=...,
    submit=...,
    share=...,
    everyone=...,
    flags=...,
    notify=...,
):
    """Share the given document with a user."""
    ...

def remove(doctype, name, user, flags=...): ...
@frappe.whitelist()
def set_permission(
    doctype, name, user, permission_to, value=..., everyone=...
):  # -> dict[Unknown, Unknown]:
    """Set share permission."""
    ...

@frappe.whitelist()
def get_users(doctype, name):
    """Get list of users with which this document is shared"""
    ...

def get_shared(doctype, user=..., rights=...):  # -> list[Unknown]:
    """Get list of shared document names for given user and DocType.

    :param doctype: DocType of which shared names are queried.
    :param user: User for which shared names are queried.
    :param rights: List of rights for which the document is shared. List of `read`, `write`, `share`"""
    ...

def get_shared_doctypes(user=...):
    """Return list of doctypes in which documents are shared for the given user."""
    ...

def get_share_name(doctype, name, user, everyone): ...
def check_share_permission(doctype, name):  # -> None:
    """Check if the user can share with other users"""
    ...

def notify_assignment(shared_by, doctype, doc_name, everyone, notify=...): ...
