"""
This type stub file was generated by pyright.
"""

def get_context(path, args=...): ...
def update_controller_context(context, controller): ...
def build_context(context):
    """get_context method of doc or module is supposed to render
    content templates and push it into context"""
    ...

def load_sidebar(context, sidebar_json_path): ...
def get_sidebar_json_path(path, look_for=...):  # -> str:
    """
    Get _sidebar.json path from directory path

    :param path: path of the current diretory
    :param look_for: if True, look for _sidebar.json going upwards from given path

    :return: _sidebar.json path
    """
    ...

def add_sidebar_and_breadcrumbs(context):  # -> None:
    """Add sidebar and breadcrumbs to context"""
    ...

def add_sidebar_data(context): ...
def add_metatags(context): ...
