"""
This type stub file was generated by pyright.
"""

def get_parent_doc(doc):  # -> None:
    """Returns document of `reference_doctype`, `reference_doctype`"""
    ...

def set_timeline_doc(doc):  # -> None:
    """Set timeline_doctype and timeline_name"""
    ...

def find(list_of_dict, match_function):  # -> None:
    """Returns a dict in a list of dicts on matching the conditions
            provided in match function

    Usage:
            list_of_dict = [{'name': 'Suraj'}, {'name': 'Aditya'}]

            required_dict = find(list_of_dict, lambda d: d['name'] == 'Aditya')
    """
    ...

def find_all(list_of_dict, match_function):  # -> list[Unknown]:
    """Returns all matching dicts in a list of dicts.
            Uses matching function to filter out the dicts

    Usage:
            colored_shapes = [
                    {'color': 'red', 'shape': 'square'},
                    {'color': 'red', 'shape': 'circle'},
                    {'color': 'blue', 'shape': 'triangle'}
            ]

            red_shapes = find_all(colored_shapes, lambda d: d['color'] == 'red')
    """
    ...

def ljust_list(_list, length, fill_word=...):  # -> list[Unknown]:
    """
    Similar to ljust but for list.

    Usage:
            $ ljust_list([1, 2, 3], 5)
            > [1, 2, 3, None, None]
    """
    ...
