"""
This type stub file was generated by pyright.
"""

from .item.item_ingka import Item as _Item_ingka
from .item.item_iows import Item as _Item_iows
from .item.item_pip import Item as _Item_pip
from .order_capture import DeliveryOptions
from .profile import PurchaseHistory, PurchaseInfo

__version__ = ...

class Item:
    def ingka(dictionary): ...
    def iows(dictionary): ...
    def pip(dictionary): ...
