"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class Comment(Document):
    def after_insert(self): ...
    def validate(self): ...
    def on_update(self): ...
    def on_trash(self): ...
    def notify_change(self, action): ...
    def remove_comment_from_cache(self): ...
    def notify_mentions(self): ...

def on_doctype_update(): ...
def update_comment_in_doc(doc):  # -> None:
    """Updates `_comments` (JSON) property in parent Document.
    Creates a column `_comments` if property does not exist.

    Only user created Communication or Comment of type Comment are saved.

    `_comments` format

            {
                    "comment": [String],
                    "by": [user],
                    "name": [Comment Document name]
            }"""
    ...

def get_comments_from_parent(doc):  # -> Any | list[Unknown]:
    """
    get the list of comments cached in the document record in the column
    `_comments`
    """
    ...

def update_comments_in_parent(reference_doctype, reference_name, _comments):  # -> None:
    """Updates `_comments` property in parent Document with given dict.

    :param _comments: Dict of comments."""
    ...

def update_comments_in_parent_after_request():  # -> None:
    """update _comments in parent if _comments column is missing"""
    ...
