"""
This type stub file was generated by pyright.
"""

import frappe

class DuplicateToDoError(frappe.ValidationError): ...

def get(args=...):
    """get assigned to"""
    ...

@frappe.whitelist()
def add(args=...):
    """add in someone's to do list
    args = {
            "assign_to": [],
            "doctype": ,
            "name": ,
            "description": ,
            "assignment_rule":
    }

    """
    ...

@frappe.whitelist()
def add_multiple(args=...): ...
def close_all_assignments(doctype, name): ...
@frappe.whitelist()
def remove(doctype, name, assign_to): ...
def set_status(doctype, name, assign_to, status=...):
    """remove from todo"""
    ...

def clear(doctype, name):  # -> bool:
    """
    Clears assignments, return False if not assigned.
    """
    ...

def notify_assignment(
    assigned_by, owner, doc_type, doc_name, action=..., description=...
):  # -> None:
    """
    Notify assignee that there is a change in assignment
    """
    ...

def format_message_for_assign_to(users): ...
