"""
This type stub file was generated by pyright.
"""

from ...api import API
from ...errors import NoDeliveryOptionsAvailableError, WrongZipCodeError
from ...utils import validate_zip_code
from ..cart import Cart

class OrderCapture(API):
    """
    API responsible for making an order.
    Use case — check available delivery services.
    """

    def __init__(self, token, zip_code) -> None: ...
    def error_handler(self, status_code, response_json): ...
    def get_delivery_services(self):  # -> Any:
        """Get available delivery services"""
        ...
