"""
This type stub file was generated by pyright.
"""

import frappe

def get_oauth_server(): ...
def sanitize_kwargs(param_kwargs):
    """Remove 'data' and 'cmd' keys, if present."""
    ...

def encode_params(params):  # -> str:
    """
    Encode a dict of params into a query string.

    Use `quote_via=urllib.parse.quote` so that whitespaces will be encoded as
    `%20` instead of as `+`. This is needed because oauthlib cannot handle `+`
    as a whitespace.
    """
    ...

@frappe.whitelist()
def approve(*args, **kwargs): ...
@frappe.whitelist(allow_guest=True)
def authorize(**kwargs): ...
@frappe.whitelist(allow_guest=True)
def get_token(*args, **kwargs): ...
@frappe.whitelist(allow_guest=True)
def revoke_token(*args, **kwargs): ...
@frappe.whitelist()
def openid_profile(*args, **kwargs): ...
@frappe.whitelist(allow_guest=True)
def openid_configuration(): ...
@frappe.whitelist(allow_guest=True)
def introspect_token(token=..., token_type_hint=...): ...
