"""
This type stub file was generated by pyright.
"""

import frappe

@frappe.whitelist()
def get(name):
    """
    Return the :term:`doclist` of the `Page` specified by `name`
    """
    ...

@frappe.whitelist(allow_guest=True)
def getpage():  # -> None:
    """
    Load the page from `frappe.form` and send it via `frappe.response`
    """
    ...

def has_permission(page): ...
