"""
This type stub file was generated by pyright.
"""

import frappe

@frappe.whitelist()
def get_all_nodes(
    doctype, label, parent, tree_method, **filters
):  # -> list[dict[str, Unknown]]:
    """Recursively gets all data from tree nodes"""
    ...

@frappe.whitelist()
def get_children(doctype, parent=..., **filters): ...
@frappe.whitelist()
def add_node(): ...
def make_tree_args(**kwarg): ...
