"""
This type stub file was generated by pyright.
"""

def validate_route_conflict(doctype, name):  # -> None:
    """
    Raises exception if name clashes with routes from other documents for /app routing
    """
    ...

def slug(name): ...
