"""
This type stub file was generated by pyright.
"""

from frappe.search.full_text_search import FullTextSearch

INDEX_NAME = ...

class WebsiteSearch(FullTextSearch):
    """Wrapper for WebsiteSearch"""

    def get_schema(self): ...
    def get_id(self): ...
    def get_items_to_index(self):  # -> list[Unknown]:
        """Get all routes to be indexed, this includes the static pages
        in www/ and routes from published documents

        Returns:
                self (object): FullTextSearch Instance
        """
        ...
    def get_document_to_index(self, route):  # -> None:
        """Render a page and parse it using BeautifulSoup

        Args:
                path (str): route of the page to be parsed

        Returns:
                document (_dict): A dictionary with title, path and content
        """
        ...
    def parse_result(self, result): ...

def slugs_with_web_view(): ...
def get_static_pages_from_all_apps(): ...
def update_index_for_path(path): ...
def remove_document_from_index(path): ...
def build_index_for_all_routes(): ...
