"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

class NavbarSettings(Document):
    def validate(self): ...
    def validate_standard_navbar_items(self): ...

@frappe.whitelist(allow_guest=True)
def get_app_logo(): ...
def get_navbar_settings(): ...
