"""
This type stub file was generated by pyright.
"""

from requests import Session

from ...constants import Constants
from ...utils import get_config_values, parse_item_code

config = ...

class ItemFetchError(Exception): ...

def build_headers(headers): ...
def generic_item_fetcher(items, headers, function, chunk_size): ...
