"""
This type stub file was generated by pyright.
"""

from typing import List

"""IOWS Item API. Works only for Russian market"""

class WrongItemCodeError(Exception): ...

def fetch(items: List[str]): ...
