"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING, Dict, List

import frappe

if TYPE_CHECKING: ...
JOB_COLORS = ...

@frappe.whitelist()
def get_info(show_failed=...) -> List[Dict]: ...
@frappe.whitelist()
def remove_failed_jobs(): ...
@frappe.whitelist()
def get_scheduler_status(): ...
