"""
This type stub file was generated by pyright.
"""

import frappe

def get_change_log(user=...): ...
def get_change_log_for_app(app, from_version, to_version): ...
@frappe.whitelist()
def update_last_known_versions(): ...
@frappe.whitelist()
def get_versions():  # -> dict[Unknown, Unknown]:
    """Get versions of all installed apps.

    Example:

            {
                    "frappe": {
                            "title": "Frappe Framework",
                            "version": "5.0.0"
                    }
            }"""
    ...

def get_app_branch(app):  # -> Literal['']:
    """Returns branch of an app"""
    ...

def get_app_last_commit_ref(app): ...
def check_for_update(): ...
def parse_latest_non_beta_release(response):  # -> None:
    """
    Parses the response JSON for all the releases and returns the latest non prerelease

    Parameters
    response (list): response object returned by github

    Returns
    json   : json object pertaining to the latest non-beta release
    """
    ...

def check_release_on_github(app: str):  # -> tuple[Version, Unknown] | None:
    """
    Check the latest release for a given Frappe application hosted on Github.

    Args:
            app (str): The name of the Frappe application.

    Returns:
            tuple(Version, str): The semantic version object of the latest release and the
                    organization name, if the application exists, otherwise None.
    """
    ...

def add_message_to_redis(update_json): ...
@frappe.whitelist()
def show_update_popup(): ...
