"""
This type stub file was generated by pyright.
"""

def make_error_snapshot(exception): ...
def get_snapshot(
    exception, context=...
):  # -> dict[str, str | Unknown | list[Unknown] | dict[Unknown, Unknown]]:
    """
    Return a dict describing a given traceback (based on cgitb.text)
    """
    ...

def collect_error_snapshots():  # -> None:
    """Scheduled task to collect error snapshots from files and push into Error Snapshot table"""
    ...

def clear_old_snapshots():  # -> None:
    """Clear snapshots that are older than a month"""
    ...

def get_error_snapshot_path(): ...
