"""
This type stub file was generated by pyright.
"""

def format_value(
    value, df=..., doc=..., currency=..., translated=...
):  # -> datetime | date | timedelta | int | float | _NotImplementedType | str | None:
    """Format value based on given fieldtype, document reference, currency reference.
    If docfield info (df) is not given, it will try and guess based on the datatype of the value"""
    ...
