"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class OAuthProviderSettings(Document): ...

def get_oauth_settings():
    """Returns oauth settings"""
    ...
