"""
This type stub file was generated by pyright.
"""

import unittest

class TestAccount(unittest.TestCase):
    def test_account_created(self): ...

def create_account(company, account_name, root_type, parent_account): ...
