"""
This type stub file was generated by pyright.
"""

from functools import wraps

from . import mutations, queries
from ...api import API
from ...utils import parse_item_code

class Cart(API):
    """API for managing cart"""

    def __init__(self, token) -> None: ...
    @_build_payload_and_call
    def show(self): ...
    @_build_payload_and_call
    def clear(self): ...
    @_build_payload_and_call
    def add_items(self, items):  # -> tuple[str, dict[str, list[Unknown]]]:
        """
        Add items to cart.
        Required items list format: [{'item_no': quantity, ...}]
        """
        ...
    @_build_payload_and_call
    def update_items(self, items):  # -> tuple[str, dict[str, list[Unknown]]]:
        """
        Replace quantity for given item to the new one.
        Required items list format: [{'item_no': quantity, ...}]
        """
        ...
    @_build_payload_and_call
    def copy_items(self, source_user_id):  # -> tuple[str, dict[str, Unknown]]:
        """Copy cart from another account"""
        ...
    @_build_payload_and_call
    def remove_items(
        self, item_codes: list
    ):  # -> tuple[str, dict[str, str | list[Unknown] | None]]:
        """
        Remove items by item codes.
        """
        ...
    @_build_payload_and_call
    def set_coupon(self, code: str): ...
    @_build_payload_and_call
    def clear_coupon(self): ...
