"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class WebsiteSlideshow(Document):
    def validate(self): ...
    def on_update(self): ...
    def validate_images(self):  # -> None:
        """atleast one image file should be public for slideshow"""
        ...

def get_slideshow(doc): ...
