"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.search.full_text_search import FullTextSearch
from frappe.search.website_search import WebsiteSearch
from frappe.utils import cint

@frappe.whitelist(allow_guest=True)
def web_search(query, scope=..., limit=...): ...
