"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import, print_function, unicode_literals

import cProfile
from functools import wraps
from os import environ
import pstats
import subprocess
import sys

import click
from six import StringIO

import frappe
import frappe.utils

def pass_context(f): ...
def get_site(context, raise_err=...): ...
def popen(command, *args, **kwargs): ...
def call_command(cmd, context): ...
def get_commands(): ...

commands = ...
