"""
This type stub file was generated by pyright.
"""

import click

from frappe.commands import pass_context

@click.command("trigger-scheduler-event", help="Trigger a scheduler event")
@click.argument("event")
@pass_context
def trigger_scheduler_event(context, event): ...
@click.command("enable-scheduler")
@pass_context
def enable_scheduler(context):  # -> None:
    "Enable scheduler"
    ...

@click.command("disable-scheduler")
@pass_context
def disable_scheduler(context):  # -> None:
    "Disable scheduler"
    ...

@click.command("scheduler")
@click.option("--site", help="site name")
@click.argument("state", type=click.Choice(["pause", "resume", "disable", "enable"]))
@pass_context
def scheduler(context, state, site=...): ...
@click.command("set-maintenance-mode")
@click.option("--site", help="site name")
@click.argument("state", type=click.Choice(["on", "off"]))
@pass_context
def set_maintenance_mode(context, state, site=...): ...
@click.command("doctor")
@click.option("--site", help="site name")
@pass_context
def doctor(context, site=...):  # -> Literal[True]:
    "Get diagnostic info about background workers"
    ...

@click.command("show-pending-jobs")
@click.option("--site", help="site name")
@pass_context
def show_pending_jobs(context, site=...):  # -> None:
    "Get diagnostic info about background jobs"
    ...

@click.command("purge-jobs")
@click.option("--site", help="site name")
@click.option("--queue", default=None, help='one of "low", "default", "high')
@click.option(
    "--event",
    default=None,
    help='one of "all", "weekly", "monthly", "hourly", "daily", "weekly_long", "daily_long"',
)
def purge_jobs(site=..., queue=..., event=...):  # -> None:
    "Purge any pending periodic tasks, if event option is not given, it will purge everything for the site"
    ...

@click.command("schedule")
def start_scheduler(): ...
@click.command("worker")
@click.option("--queue", type=str)
@click.option("--quiet", is_flag=True, default=False, help="Hide Log Outputs")
def start_worker(queue, quiet=...): ...
@click.command("ready-for-migration")
@click.option("--site", help="site name")
@pass_context
def ready_for_migration(context, site=...): ...

commands = ...
