"""
This type stub file was generated by pyright.
"""

import click

from frappe.commands import pass_context

@click.command("build-message-files")
@pass_context
def build_message_files(context):  # -> None:
    "Build message files for translation"
    ...

@click.command("new-language")
@pass_context
@click.argument("lang_code")
@click.argument("app")
def new_language(context, lang_code, app):  # -> None:
    """Create lang-code.csv for given app"""
    ...

@click.command("get-untranslated")
@click.argument("lang")
@click.argument("untranslated_file")
@click.option("--all", default=False, is_flag=True, help="Get all message strings")
@pass_context
def get_untranslated(context, lang, untranslated_file, all=...):  # -> None:
    "Get untranslated strings for language"
    ...

@click.command("update-translations")
@click.argument("lang")
@click.argument("untranslated_file")
@click.argument("translated-file")
@pass_context
def update_translations(context, lang, untranslated_file, translated_file):  # -> None:
    "Update translated strings"
    ...

@click.command("import-translations")
@click.argument("lang")
@click.argument("path")
@pass_context
def import_translations(context, lang, path):  # -> None:
    "Update translated strings"
    ...

commands = ...
