"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class DynamicLink(Document): ...

def on_doctype_update(): ...
def deduplicate_dynamic_links(doc): ...
