"""
This type stub file was generated by pyright.
"""

import sys

from frappe.integrations.frappe_providers.frappecloud import (
    frappecloud_migrator,
)

def migrate_to(local_site, frappe_provider): ...
