"""
This type stub file was generated by pyright.
"""

from __future__ import print_function, unicode_literals

import io
import re

from six import text_type
from six.moves import range

import frappe
from frappe import _
from frappe.build import html_to_js_template
from frappe.utils import cstr

STANDARD_FIELD_CONVERSION_MAP = ...

def set_default(doc, key):  # -> None:
    """Set is_default property of given doc and unset all others filtered by given key."""
    ...

def set_field_property(filters, key, value):  # -> None:
    """utility set a property in all fields of a particular type"""
    ...

class InvalidIncludePath(frappe.ValidationError): ...

def render_include(content):  # -> str:
    """render {% raw %}{% include "app/path/filename" %}{% endraw %} in js file"""
    ...

def get_fetch_values(doctype, fieldname, value):  # -> dict[Unknown, Unknown]:
    """Returns fetch value dict for the given object

    :param doctype: Target doctype
    :param fieldname: Link fieldname selected
    :param value: Value selected
    """
    ...
