"""
This type stub file was generated by pyright.
"""

ignore_doctypes = ...

def notify_link_count(doctype, name):  # -> None:
    """updates link count for given document"""
    ...

def flush_local_link_count():  # -> None:
    """flush from local before ending request"""
    ...

def update_link_count():  # -> None:
    """increment link count in the `idx` column for the given document"""
    ...
