"""
This type stub file was generated by pyright.
"""

import frappe

@frappe.whitelist()
def get_data_keys(): ...
@frappe.whitelist()
def upload(
    rows=...,
    submit_after_import=...,
    ignore_encoding_errors=...,
    no_email=...,
    overwrite=...,
    update_only=...,
    ignore_links=...,
    pre_process=...,
    via_console=...,
    from_data_import=...,
    skip_errors=...,
    data_import_doc=...,
    validate_template=...,
    user=...,
):  # -> dict[str, list[Unknown] | bool] | Literal[True] | None:
    """upload data"""
    ...

def get_parent_field(doctype, parenttype): ...
def delete_child_rows(rows, doctype):  # -> None:
    """delete child rows for all parents"""
    ...
