"""
This type stub file was generated by pyright.
"""

def migrate(verbose=..., skip_failing=..., skip_search_index=...):  # -> None:
    """Migrate all apps to the current version, will:
    - run before migrate hooks
    - run patches
    - sync doctypes (schema)
    - sync dashboards
    - sync fixtures
    - sync desktop icons
    - sync web pages (from /www)
    - sync web pages (from /www)
    - run after migrate hooks
    """
    ...
