name: Backup

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: 0 */6 * * * # every 6 hours

jobs:
  backup:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - uses: actions/checkout@v2

      - name: Copy files
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          source: docker/scripts/backup.sh
          target: comfort
          strip_components: 1

      - name: Backup
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          envs: BUCKET_NAME,REGION,ACCESS_KEY_ID,SECRET_ACCESS_KEY,ENDPOINT_URL
          script_stop: true
          script: |
            cd comfort
            BUCKET_NAME=$BUCKET_NAME \
              REGION=$REGION \
              ACCESS_KEY_ID=$ACCESS_KEY_ID \
              SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY \
              ENDPOINT_URL=$ENDPOINT_URL \
              bash scripts/backup.sh
            rm -rf scripts
        env:
          BUCKET_NAME: ${{ secrets.S3_BACKUP_BUCKET_NAME }}
          REGION: ${{ secrets.S3_BACKUP_REGION }}
          ACCESS_KEY_ID: ${{ secrets.S3_BACKUP_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.S3_BACKUP_SECRET_ACCESS_KEY }}
          ENDPOINT_URL: ${{ secrets.S3_BACKUP_ENDPOINT_URL }}
