name: Backup

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */6 * * * # every 6 hours

jobs:
  backup:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - uses: actions/checkout@v2
      - name: Backup
        uses: ./.github/actions/backup
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          bucket_name: ${{ secrets.S3_BACKUP_BUCKET_NAME }}
          region: ${{ secrets.S3_BACKUP_REGION }}
          access_key_id: ${{ secrets.S3_BACKUP_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.S3_BACKUP_SECRET_ACCESS_KEY }}
          endpoint_url: ${{ secrets.S3_BACKUP_ENDPOINT_URL }}
