name: Deployment

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * * # every day at 3 AM

concurrency: server

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.YANDEX_TOKEN }}

      - name: Get latest Comfort version
        run: echo COMFORT_VERSION=v$(awk -F '"' '/__version__/{print $2}' setup.py) >>$GITHUB_ENV

      - name: Generate .env
        run: |
          docker manifest inspect cr.yandex/crpdmuh1072ntg30t18g/comfort-nginx:$COMFORT_VERSION
          if [ $? -ne 0 ]; then echo "No image with tag $COMFORT_VERSION" && exit 1; fi
          cd docker
          bash scripts/generate-env.sh
        env:
          COMFORT_VERSION: ${{ env.COMFORT_VERSION }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DOMAIN: ${{ secrets.DOMAIN }}
          LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

      - name: Backup
        uses: ./.github/actions/backup
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          bucket_name: ${{ secrets.S3_BACKUP_BUCKET_NAME }}
          region: ${{ secrets.S3_BACKUP_REGION }}
          access_key_id: ${{ secrets.S3_BACKUP_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.S3_BACKUP_SECRET_ACCESS_KEY }}
          endpoint_url: ${{ secrets.S3_BACKUP_ENDPOINT_URL }}

      - name: Copy files
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          source: docker/docker-compose.yml,docker/.env,docker/scripts/deploy.sh,docker/scripts/check-health.sh
          target: comfort
          strip_components: 1

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          envs: COMFORT_VERSION
          script_stop: true
          script: |
            cd comfort
            COMFORT_VERSION=$COMFORT_VERSION bash scripts/deploy.sh
            rm -rf scripts
        env:
          COMFORT_VERSION: ${{ env.COMFORT_VERSION }}
