name: Docker

on:
  release:
    types:
      - published
  pull_request:
    # paths:
    #   - docker/**
    #   - .dockerignore
    #   - comfort/hooks.py # contains `reqd_frappe_version`

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1.6.0
      - uses: docker/login-action@v1.10.0
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.YANDEX_TOKEN }}

      - name: Set up build args
        run: |
          set -x

          echo FRAPPE_VERSION=$(awk -F '"' '/reqd_frappe_version/{print $2}' comfort/hooks.py) >>$GITHUB_ENV
          echo TAG=${GITHUB_REF##*/} >>$GITHUB_ENV
          echo $FRAPPE_VERSION
          echo $TAG

      # - name: Build images
      #   uses: docker/bake-action@v1.6.0
      #   with:
      #     load: true

      # - name: Smoke Test
      #   working-directory: docker
      #   run: bash scripts/smoke-test.sh
      #   env:
      #     COMFORT_VERSION: ${{ fromJSON(steps.nginx-meta.outputs.json).labels['org.opencontainers.image.version'] }}

      # - name: Push images
      #   if: github.event_name != 'pull_request'
      #   uses: docker/bake-action@v1.6.0
      #   with:
      #     push: true
