name: Docker

on:
  release:
    types:
      - published
  pull_request:
    paths:
      - docker/**
      - .dockerignore

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.YANDEX_TOKEN }}

      - name: Set up build args
        run: echo FRAPPE_VERSION=$(awk -F '"' '/reqd_frappe_version/{print $2}' comfort/hooks.py) >>$GITHUB_ENV

      - name: Nginx meta
        id: nginx-meta
        uses: docker/metadata-action@v3
        with:
          images: cr.yandex/crpdmuh1072ntg30t18g/comfort-nginx

      - name: Worker meta
        id: worker-meta
        uses: docker/metadata-action@v3
        with:
          images: cr.yandex/crpdmuh1072ntg30t18g/comfort-worker

      - name: Build Nginx image
        uses: docker/build-push-action@v2
        with:
          file: docker/nginx.Dockerfile
          build-args: FRAPPE_VERSION=${{ env.FRAPPE_VERSION }}
          pull: true
          load: true
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ steps.nginx-meta.outputs.tags }}
          labels: ${{ steps.nginx-meta.outputs.labels }}

      - name: Build Worker image
        uses: docker/build-push-action@v2
        with:
          file: docker/worker.Dockerfile
          build-args: FRAPPE_VERSION=${{ env.FRAPPE_VERSION }}
          pull: true
          load: true
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ steps.worker-meta.outputs.tags }}
          labels: ${{ steps.worker-meta.outputs.labels }}

      - name: Smoke Test
        run: |
          export COMFORT_VERSION=${{ fromJSON(steps.nginx-meta.outputs.json).labels['org.opencontainers.image.version'] }}
          cd docker
          bash scripts/smoke-test.sh

      - name: Push Nginx image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          file: docker/nginx.Dockerfile
          build-args: FRAPPE_VERSION=${{ env.FRAPPE_VERSION }}
          push: true
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ steps.nginx-meta.outputs.tags }}
          labels: ${{ steps.nginx-meta.outputs.labels }}

      - name: Push Worker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          file: docker/worker.Dockerfile
          build-args: FRAPPE_VERSION=${{ env.FRAPPE_VERSION }}
          push: true
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ steps.worker-meta.outputs.tags }}
          labels: ${{ steps.worker-meta.outputs.labels }}
