name: Release

on:
  push:
    branches:
      - prod

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install python-semantic-release
        run: pip install python-semantic-release

      - name: Setup git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"

      - name: Release
        run: semantic-release publish -D commit_author="github-actions <action@github.com>"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
