name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install python-semantic-release
        run: pip install python-semantic-release

      - name: Setup git config
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Release
        run: semantic-release publish -D commit_author="github-actions <github-actions@github.com>"
        env:
          # https://github.community/t/github-actions-workflow-not-triggering-with-tag-push/17053
          GH_TOKEN: ${{ secrets.PAT }}
