name: Test Authorization Server

on:
  workflow_dispatch:
  push:
    paths:
      - authorization_server/**
  pull_request:
    paths:
      - authorization_server/**

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: authorization_server

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('authorization_server/requirements.txt') }}

      - name: Install
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Test
        run: pytest --color=yes
