name: Test Browser Extension

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - browser_ext/**
      - "!browser_ext/chrome/**"
  pull_request:
    paths:
      - browser_ext/**
      - "!browser_ext/chrome/**"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: browser_ext

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('browser_ext/setup.py') }}

      - name: Install
        run: pip install .[dev]

      - name: Test
        run: pytest --color=yes
