"""
This type stub file was generated by pyright.
"""

import frappe

no_cache = ...

def get_context(context, **dict_params):  # -> None:
    """Returns context for a list standard list page.
    Will also update `get_list_context` from the doctype module file"""
    ...

@frappe.whitelist(allow_guest=True)
def get(
    doctype, txt=..., limit_start=..., limit=..., pathname=..., **kwargs
):  # -> dict[str, list[Unknown]] | dict[str, str | Unknown | list[Unknown]]:
    """Returns processed HTML page for a standard listing."""
    ...

@frappe.whitelist(allow_guest=True)
def get_list_data(
    doctype,
    txt=...,
    limit_start=...,
    fields=...,
    cmd=...,
    limit=...,
    web_form_name=...,
    **kwargs,
):
    """Returns processed HTML page for a standard listing."""
    ...

def set_route(context):  # -> None:
    """Set link for the list item"""
    ...

def prepare_filters(doctype, controller, kwargs): ...
def get_list_context(context, doctype, web_form_name=...): ...
def get_list(
    doctype,
    txt,
    filters,
    limit_start,
    limit_page_length=...,
    ignore_permissions=...,
    fields=...,
    order_by=...,
): ...
