"""
This type stub file was generated by pyright.
"""

import frappe

@frappe.whitelist()
@frappe.read_only()
def get_notifications(): ...
def get_notifications_for_doctypes(
    config, notification_count
):  # -> dict[Unknown, Unknown]:
    """Notifications for DocTypes"""
    ...

def get_notifications_for_targets(
    config, notification_percent
):  # -> dict[Unknown, Unknown]:
    """Notifications for doc targets"""
    ...

def clear_notifications(user=...): ...
def clear_notification_config(user): ...
def delete_notification_count_for(doctype): ...
def clear_doctype_notifications(doc, method=..., *args, **kwargs): ...
@frappe.whitelist()
def get_notification_info(): ...
def get_notification_config(): ...
def get_filters_for(doctype):  # -> None:
    """get open filters for doctype"""
    ...

@frappe.whitelist()
@frappe.read_only()
def get_open_count(doctype, name, items=...):  # -> dict[str, list[Unknown]]:
    """Get open count for given transactions and filters

    :param doctype: Reference DocType
    :param name: Reference Name
    :param transactions: List of transactions (json/dict)
    :param filters: optional filters (json/list)"""
    ...
