"""
This type stub file was generated by pyright.
"""

import wrapt

import frappe

UNTRANSLATED_DOCTYPES = ...

def sanitize_searchfield(searchfield): ...
@frappe.whitelist()
def search_link(
    doctype,
    txt,
    query=...,
    filters=...,
    page_length=...,
    searchfield=...,
    reference_doctype=...,
    ignore_user_permissions=...,
): ...
@frappe.whitelist()
def search_widget(
    doctype,
    txt,
    query=...,
    searchfield=...,
    start=...,
    page_length=...,
    filters=...,
    filter_fields=...,
    as_dict=...,
    reference_doctype=...,
    ignore_user_permissions=...,
): ...
def get_std_fields_list(meta, key): ...
def build_for_autosuggest(res): ...
def scrub_custom_query(query, key, txt): ...
@wrapt.decorator
def validate_and_sanitize_search_inputs(fn, instance, args, kwargs): ...
@frappe.whitelist()
def get_names_for_mentions(search_term): ...
def get_users_for_mentions(): ...
def get_user_groups(): ...
